// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://www.integrator.com/terms",
        "contact": {
            "name": "API Support",
            "url": "https://www.Integrator.com/support",
            "email": "support@Integrator.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/init": {
            "post": {
                "description": "Lancer l'initialisation de l'application",
                "tags": [
                    "app"
                ],
                "summary": "Initialisation de l'application",
                "responses": {}
            }
        },
        "/api/users/": {
            "get": {
                "description": "Recuperation de tous les utilisateurs",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "users"
                ],
                "summary": "APIGetAll",
                "responses": {}
            },
            "post": {
                "description": "Creation d'un nouvel utilisateur",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "users"
                ],
                "summary": "APICreate",
                "responses": {}
            }
        },
        "/api/users/:id": {
            "get": {
                "description": "Lecture des informations d'un utilisateur",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "users"
                ],
                "summary": "APIRead",
                "responses": {}
            },
            "put": {
                "description": "Mise à jours des informations d'un utilisateur",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "users"
                ],
                "summary": "APIUpdate",
                "responses": {}
            },
            "delete": {
                "description": "Suppression d'un utilisateur",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "users"
                ],
                "summary": "APIDelete",
                "responses": {}
            }
        },
        "/api/users/login": {
            "post": {
                "description": "Connexion",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "users"
                ],
                "summary": "APILogin",
                "responses": {}
            }
        }
    },
    "securityDefinitions": {
        "": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "core-api.Integrator.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Integrator Core API",
	Description:      "API Core.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
