version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always

    environment:
      POSTGRES_DB: spay
      POSTGRES_USER: spay
      POSTGRES_PASSWORD: thesecret

    ports:
      - '5432:5432'
    volumes:
      - local_pgdata:/var/lib/postgresql/data

    networks:
      postgres-net:

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: thesecret

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    networks:
      postgres-net:

  keycloak:
    image: auth-keycloak
    build:
      context: .
      dockerfile: ./dockerfile-keycloak.yml
    command: start --optimized --hostname-port=8080 --https-key-store-file=/opt/keycloak/conf/server.keystore

    networks:
      postgres-net:

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: spay
      KC_DB_PASSWORD: thesecret
      KC_HOSTNAME: localhost
      KEYCLOAK_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: thesecret
      KC_HTTP_ENABLED: true

    ports:
      - 8080:8443

    volumes:
      - keycloak_data:/opt/keycloak

    depends_on:
      - postgres

  authservice:
    image: auth-service:latest
    restart: always

    ports:
      - "3001:3000"

    networks:
      postgres-net:

    environment:
      PORT_API: 3000
      KEYCLOAK_HOST: https://keycloak:8443
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: thesecret
      KEYCLOAK_ADMIN_REALM: master
      KEYCLOAK_CLIENT_ID: authservice
      KEYCLOAK_CLIENT_SECRET: 8PbwjgVNKmzEXU6bYJlRKFTm6ypEKDkM
      KEYCLOAK_CLIENT_REALM: master
      DB_PROVIDER: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: authservice
      DB_USER: spay
      DB_PASS: thesecret
      DB_INIT: true

    depends_on:
      - postgres

networks:
  postgres-net:

volumes:
  local_pgdata:
  pgadmin_data:
  keycloak_data:
