PORT_API: 3000

# Keycloak
KEYCLOAK_HOST:
KEYCLOAK_CLIENT_ID:
KEYCLOAK_CLIENT_SECRET:
KEYCLOAK_CLIENT_REALM:

# Database
DB_PROVIDER: pg
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: spay
DB_USER: spay
DB_PASS: thesecret
DB_INIT: true

# SMTP
SMTP_FROM:
SMTP_HOST:
SMTP_PORT:
SMTP_START_TLS:
SMTP_USER:
SMTP_PASS:
